
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('restaurants').del()
    .then(function () {
      // Inserts seed entries
      return knex('restaurants').insert([
        {
          net_rating: 5,
          pricing: "$$",
          restaurant_name: 'Midnight Espresso',
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-w/0e/70/1b/da/photo2jpg.jpg",
          address: "178 Cuba St, Te Aro, Wellington 6011",
          phone: "006443847014",
          description: "Warm, cosy, and yummy!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 1,
          pricing: "$$",
          restaurant_name: 'Deluxe cafe',
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/03/5e/87/54/deluxe-at-the-embassy.jpg",
          address: "10 Kent Terrace, Mount Victoria, Wellington 6011",
          phone:"006448015455",
          description: "All about the coffee",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: false
        },
        {
          net_rating: 9,
          pricing: "$$$",
          restaurant_name: 'Enigma Cafe',
          restaurant_url: "http://enigmacafe.co.nz/2017/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0b/09/93/4e/enigma.jpg",
          address: "128 Courtenay Pl, Te Aro, Wellington 6011",
          phone: "006443852905"
          description: "Good food, great service",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 3,
          pricing: "$$",
          restaurant_name: "Fidel's Cafe",
          restaurant_url: "http://www.fidelscafe.com/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/56/b3/b1/photo0jpg.jpg",
          address: "234 Cuba St, Te Aro, Wellington 6011",
          phone: "006448016868",
          description: "Cuban tastes",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 8,
          pricing: "$$",
          restaurant_name: "Burger Liquor",
          restaurant_url: "http://www.burgerliquor.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/56/b3/b1/photo0jpg.jpg",
          address: "129 Willis St, Te Aro, Wellington 6011",
          phone: "006443851104",
          description: "Cool atmosphere, good burgers",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: false
        },
        {
          net_rating: 8,
          pricing: "$",
          restaurant_name: "Astoria",
          restaurant_url: "http://www.astoria.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/03/a3/ee/20/astoria.jpg",
          address: "159 Lambton Quay, Wellington 6011",
          phone: "006444738500",
          description: "Great place for breakfast",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 18,
          pricing: "$",
          restaurant_name: "Baobab Wellington",
          restaurant_url: "http://baobabcafe.co.nz/",
          image_url: "http://baobabcafe.co.nz/wp-content/uploads/coffee-hands.jpg",
          address: "152 Riddiford St, Newtown, Wellington 6021",
          phone: "006443800470"
          description: "Coffee with turmeric - the perfect winter warmer!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 6,
          pricing: "$$",
          restaurant_name: "Flight Coffee Hangar",
          restaurant_url: "https://flightcoffee.co.nz/hangar",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/07/03/63/3a/flight-coffee-hangar.jpg",
          address: "119 Dixon St, Te Aro, Wellington 6011",
          phone: "006448300909",
          description: "Great coffee!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 16,
          pricing: "$",
          restaurant_name: "Laundry",
          restaurant_url: "http://www.laundry.net.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/06/26/17/8c/relaxing-at-laundry.jpg",
          address: "242 Cuba St, Te Aro, Wellington 6011",
          phone: "006443844280",
          description: "Fun spot, great service",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 10,
          pricing: "$",
          restaurant_name: "Maranui Cafe",
          restaurant_url: "http://www.laundry.net.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/06/26/17/8c/relaxing-at-laundry.jpg",
          address: "7 Lyall Parade, Lyall Bay, Wellington 6022",
          phone: "006443844280",
          description: "Fun spot, great service",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 16,
          pricing: "$$",
          restaurant_name: "Queen Sally's Diamond Deli",
          restaurant_url: "http://www.queens.co.nz/about.html",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/06/5e/26/23/queen-sally-s-diamond.jpg",
          address: "200 Queens Dr, Lyall Bay, Wellington 6022",
          phone: "006443872829",
          description: "Queen Sally's Diamond Deli is a true testament to the strength of coffee. Like a phoenix, it rose from the ashes of fire-ravaged Maranui Café, opening in Queen's Drive to quell the rumbling stomachs of Lyall Bay.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 10,
          pricing: "$",
          restaurant_name: "Monterey Bar",
          restaurant_url: "https://montereynewtown.co.nz/index.html",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0c/a2/99/a9/monterey-bar.jpg",
          address: "4 Rintoul St, Newtown, Wellington 6021",
          phone: "0064210474530",
          description: "Monterey is a neighbourhood bar and diner established in Newtown in 2010. We serve independent beers and sodas, burgers made with homemade sauces, house-smoked meats and quality produce. Our kitchen serves great food seven days a week. Where possible our ingredients are organic, free-range and ethically sourced. We have tables you can sketch on, a sunny backyard, friendly staff, excellent music, and games that remind you of being a kid.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 13,
          pricing: "$$$",
          restaurant_name: "Neo Cafe",
          restaurant_url: "https://www.neocafe.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0d/d0/c4/c5/veggie-brekkie-gf.jpg",
          address: "132 Willis St, Te Aro, Wellington 6011",
          phone: "006443859553",
          description: "Neo Cafe & Eatery offers contemporary NZ cafe cuisine celebrating local artisan producers & suppliers and is continually developing exciting offerings for Wellington’s legion of foodies.Our seasonal menu specialises in all day brunch, fresh salads, in-house baking and caters to a range of diets including gluten-free, vegetarian, and vegan. Neo has a clean modern aesthetic which offers a relaxed environment to our inner-city clientele.We’d love to seat you at a table so you can enjoy the warmth of our space and the excellent coffee, beverage and food offerings.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 9,
          pricing: "$",
          restaurant_name: "Rahzoo",
          restaurant_url: "https://www.neocafe.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/09/00/97/0a/rahzoo-cafe.jpg",
          address: "32 Waring Taylor St, Wellington, 6011",
          phone: "006444726815",
          description: "Best cheese scones in town!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },


      ]);
    });
};
