
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('restaurants').del()
    .then(function () {
      // Inserts seed entries
      return knex('restaurants').insert([
        {
          net_rating: 5,
          pricing: "$$",
          restaurant_name: 'Midnight Espresso',
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-w/0e/70/1b/da/photo2jpg.jpg",
          address: "178 Cuba St, Te Aro, Wellington 6011",
          lat:"-41.2945429",
          lng:"174.7748678",
          phone: "006443847014",
          description: "Warm, cosy, and yummy!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 1,
          pricing: "$$",
          restaurant_name: 'Deluxe cafe',
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/03/5e/87/54/deluxe-at-the-embassy.jpg",
          address: "10 Kent Terrace, Mount Victoria, Wellington 6011",
          lat:"-41.2943203",
          lng:"174.7840576",
          phone:"006448015455",
          description: "All about the coffee",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: false
        },
        {
          net_rating: 9,
          pricing: "$$$",
          restaurant_name: 'Enigma Cafe',
          restaurant_url: "http://enigmacafe.co.nz/2017/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0b/09/93/4e/enigma.jpg",
          address: "128 Courtenay Pl, Te Aro, Wellington 6011",
          lat:"-41.2924698",
          lng:"174.7793674",
          phone: "006443852905",
          description: "Good food, great service",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 3,
          pricing: "$$",
          restaurant_name: "Fidel's Cafe",
          restaurant_url: "http://www.fidelscafe.com/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/56/b3/b1/photo0jpg.jpg",
          address: "234 Cuba St, Te Aro, Wellington 6011",
          lat:"-41.2959071",
          lng:"174.7739487",
          phone: "006448016868",
          description: "Cuban tastes",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 8,
          pricing: "$$",
          restaurant_name: "Burger Liquor",
          restaurant_url: "http://www.burgerliquor.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/56/b3/b1/photo0jpg.jpg",
          address: "129 Willis St, Te Aro, Wellington 6011",
          lat:"-41.2898022",
          lng:"174.7744975",
          phone: "006443851104",
          description: "Cool atmosphere, good burgers",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: false
        },
        {
          net_rating: 8,
          pricing: "$",
          restaurant_name: "Astoria",
          restaurant_url: "http://www.astoria.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/03/a3/ee/20/astoria.jpg",
          address: "159 Lambton Quay, Wellington 6011",
          lat:"-41.2825527",
          lng:"174.7765304",
          phone: "006444738500",
          description: "Great place for breakfast",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 18,
          pricing: "$",
          restaurant_name: "Baobab Wellington",
          restaurant_url: "http://baobabcafe.co.nz/",
          image_url: "http://baobabcafe.co.nz/wp-content/uploads/coffee-hands.jpg",
          address: "152 Riddiford St, Newtown, Wellington 6021",
          lat:"-41.3130669",
          lng:"174.7794356",
          phone: "006443800470",
          description: "Coffee with turmeric - the perfect winter warmer!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 6,
          pricing: "$$",
          restaurant_name: "Flight Coffee Hangar",
          restaurant_url: "https://flightcoffee.co.nz/hangar",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/07/03/63/3a/flight-coffee-hangar.jpg",
          address: "119 Dixon St, Te Aro, Wellington 6011",
          lat:"-41.2907929",
          lng:"174.7735663",
          phone: "006448300909",
          description: "Great coffee!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 16,
          pricing: "$",
          restaurant_name: "Laundry",
          restaurant_url: "http://www.laundry.net.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/06/26/17/8c/relaxing-at-laundry.jpg",
          address: "242 Cuba St, Te Aro, Wellington 6011",
          lat:"-41.2961319",
          lng:"174.7740165",
          phone: "006443844280",
          description: "Fun spot, great service",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 10,
          pricing: "$",
          restaurant_name: "Maranui Cafe",
          restaurant_url: "http://www.laundry.net.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/06/26/17/8c/relaxing-at-laundry.jpg",
          address: "7 Lyall Parade, Lyall Bay, Wellington 6022",
          lat:"-41.3304322",
          lng:"174.7933458",
          phone: "006443844280",
          description: "Fun spot, great service",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 16,
          pricing: "$$",
          restaurant_name: "Queen Sally's Diamond Deli",
          restaurant_url: "http://www.queens.co.nz/about.html",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/06/5e/26/23/queen-sally-s-diamond.jpg",
          address: "200 Queens Dr, Lyall Bay, Wellington 6022",
          lat:"-41.3307173",
          lng:"174.7915316",
          phone: "006443872829",
          description: "Queen Sally's Diamond Deli is a true testament to the strength of coffee. Like a phoenix, it rose from the ashes of fire-ravaged Maranui Café, opening in Queen's Drive to quell the rumbling stomachs of Lyall Bay.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 10,
          pricing: "$",
          restaurant_name: "Monterey Bar",
          restaurant_url: "https://montereynewtown.co.nz/index.html",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0c/a2/99/a9/monterey-bar.jpg",
          address: "4 Rintoul St, Newtown, Wellington 6021",
          lat:"-41.3118045",
          lng:"174.7790072",
          phone: "0064210474530",
          description: "Monterey is a neighbourhood bar and diner established in Newtown in 2010. We serve independent beers and sodas, burgers made with homemade sauces, house-smoked meats and quality produce. Our kitchen serves great food seven days a week. Where possible our ingredients are organic, free-range and ethically sourced. We have tables you can sketch on, a sunny backyard, friendly staff, excellent music, and games that remind you of being a kid.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 13,
          pricing: "$$$",
          restaurant_name: "Neo Cafe",
          restaurant_url: "https://www.neocafe.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0d/d0/c4/c5/veggie-brekkie-gf.jpg",
          address: "132 Willis St, Te Aro, Wellington 6011",
          lat:"-41.2894575",
          lng:"174.7743433",
          phone: "006443859553",
          description: "Neo Cafe & Eatery offers contemporary NZ cafe cuisine celebrating local artisan producers & suppliers and is continually developing exciting offerings for Wellington’s legion of foodies.Our seasonal menu specialises in all day brunch, fresh salads, in-house baking and caters to a range of diets including gluten-free, vegetarian, and vegan. Neo has a clean modern aesthetic which offers a relaxed environment to our inner-city clientele.We’d love to seat you at a table so you can enjoy the warmth of our space and the excellent coffee, beverage and food offerings.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 9,
          pricing: "$",
          restaurant_name: "Rahzoo",
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/09/00/97/0a/rahzoo-cafe.jpg",
          address: "32 Waring Taylor St, Wellington, 6011",
          lat:"-41.282125",
          lng:"174.776951",
          phone: "006444726815",
          description: "Best cheese scones in town!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 11,
          pricing: "$$",
          restaurant_name: "Southern Cross Garden Bar Restaurant",
          restaurant_url: "https://www.thecross.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/d2/69/29/the-restaurant.jpg",
          address: "39 Abel Smith St, Te Aro, Wellington 6011",
          lat:"-41.2964952",
          lng:"174.7744768",
          phone: "006443849085",
          description: "For over 100 years our place here in Te Aro, Wellington, has been a favourite meeting place for locals. We love being a part of the community and we are ready to throw in the hard yards to make sure everyone who visits us has a great experience. The Cross has something for everyone - have a look around and choose the perfect spot to suit your mood. Each area has been designed to create a different experience, a different ambience. Bring in your team from work, your mates, your kids, your grandparents, your study group, your special someone, your laptop, your dog (in the garden bar!) or your party guests – we can set you up with a space, top-notch food and drinks to suit your occasion.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 6,
          pricing: "$$$",
          restaurant_name: "Zibibbo Wellington",
          restaurant_url: "http://www.zibibbo.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/e4/d8/a6/crispy-skin-free-range.jpg",
          address: "25-29 Taranaki St, Te Aro, Wellington 6011",
          lat:"-41.2916855",
          lng:"174.7795819",
          phone: "006443856650",
          description: "For over 100 years our place here in Te Aro, Wellington, has been a favourite meeting place for locals. We love being a part of the community and we are ready to throw in the hard yards to make sure everyone who visits us has a great experience. The Cross has something for everyone - have a look around and choose the perfect spot to suit your mood. Each area has been designed to create a different experience, a different ambience. Bring in your team from work, your mates, your kids, your grandparents, your study group, your special someone, your laptop, your dog (in the garden bar!) or your party guests – we can set you up with a space, top-notch food and drinks to suit your occasion.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 16,
          pricing: "$",
          restaurant_name: "Gotham Cafe and Bar",
          restaurant_url: "https://gotham.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0b/0e/34/79/gotham-cafe.jpg",
          address: "4 Chews Ln, Wellington, 6011",
          lat:"-41.2874775",
          lng:"174.776393",
          phone: "00649106009",
          description: "Gotham has for years now, been one of Wellington’s best-loved independent Cafes. Situated right in the heart of the city in the very stylish Chews Lane precinct, Gotham Cafe & Bar is a haven from the capital’s mercurial weather – warm in winter, while in summer the large bi-fold doors are swung open to create a relaxing place to enjoy the day. Coffee and freshly prepared home-style food is the hallmark of Gotham, which offers the best organic Havana blend, organic milk, local produce where possible, cafe style meals, your favourite wine or beer in a low-key atmosphere.",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 7,
          pricing: "$",
          restaurant_name: "Seize",
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-w/08/53/f6/a2/seize-cafe.jpg",
          address: "117 Lambton Quay, Wellington, 6011",
          lat:"-41.2810346",
          lng:"174.7760794",
          phone: "0064274585886",
          description: "All my favourites - perfect for gluten free!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: false,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 2,
          pricing: "$$",
          restaurant_name: "The Botanist",
          restaurant_url: "http://thebotanistlyallbay.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0f/4a/7c/4e/photo1jpg.jpg",
          address: "219 Onepu Rd, Lyall Bay, Wellington 6022",
          lat:"-41.3288544",
          lng:"174.7954628",
          phone: "006448910198",
          description: "The Botanist is Lyall Bay's latest addition to the beautiful south coast, bringing the best in tasty organic vegetarian & vegan fare. Views to the sea, with a sunny north facing courtyard, six rotating craft beer taps, botanical cocktails, vegan & organic wines.",
          is_meat: false,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 12,
          pricing: "$$$",
          restaurant_name: "Cin Cin",
          restaurant_url: "http://www.cincin.net.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/1f/4b/38/photo0jpg.jpg",
          address: "156 Cuba St, Te Aro, Wellington 6011",
          lat:"-41.2940558",
          lng:"174.775136",
          phone: "006443852462",
          description: "Great food and wonderful staff",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {

          net_rating: 8,
          pricing: "$",
          restaurant_name: "Tommy Millions",
          restaurant_url: "https://www.tommymillions.co.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-w/03/bb/16/3f/tommy-millions.jpg",
          address: "105 Courtenay Pl, Te Aro, Wellington 6011",
          lat:"-41.2927307",
          lng:"174.7788817",
          phone: "006443828866",
          description: "Laverly special pizza of the day and great veggie options",
          is_meat: true,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 4,
          pricing: "$$$",
          restaurant_name: "Hippopotamus Restaurant and Cocktail Bar",
          restaurant_url: "https://www.qthotelsandresorts.com/wellington/eat-drink/hippopotamus/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/3f/66/f9/hippopotamus-restaurant.jpg",
          address: "Museum Art Hotel, Level 3, 90 Cable St, Te Aro, Wellington 6011",
          lat:"-41.2918229",
          lng:"174.7824664",
          phone: "006448028935",
          description: "When you are looking for a delicious dining experience in a stunning setting try our flagship, French inspired restaurant – Hippopotamus. Our broad menu is peppered with a delicious mix of comfort food and fine-dining dishes that are designed to satisfy your hunger.Our skilled service team will weave their way in and out of your experience ready to recommend their favourite dish and aperitif. In our adjoining Cocktail Bar mixologists armed with all the hip, new cocktails and a host of firm favourites that can either be enjoyed while you dine, or as a pre and post dining spot.Perfect for people watching in Wellywood!",
          is_meat: true,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: false
        },
        {
          net_rating: 14,
          pricing: "$",
          restaurant_name: "Aunty Mena's Vegetarian Cafe Restaurant",
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/0d/e7/c4/dd/photo3jpg.jpg",
          address: "167 Cuba St, Te Aro, Wellington 6011",
          lat:"-41.2940181",
          lng:"174.7754852",
          phone: "006443828288",
          description: "Great meal, great value.",
          is_meat: false,
          is_vegan: true,
          is_breakfast: false,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: false
        },
        {
          net_rating: 6,
          pricing: "$",
          restaurant_name: "Satay Kingdom",
          restaurant_url: "",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/03/a4/36/6d/satay-kingdom.jpg",
          address: "212 Cuba St, Te Aro, Wellington 6011",
          lat:"-41.2953803",
          lng:"174.7743624",
          phone: "006443813730",
          description: "Hidden Treasure in Wellington",
          is_meat: true,
          is_vegan: false,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        },
        {
          net_rating: 12,
          pricing: "$$",
          restaurant_name: "Boquita",
          restaurant_url: "http://boquita.nz/",
          image_url: "https://media-cdn.tripadvisor.com/media/photo-o/10/3b/4b/c7/img-20170811-132653-largejpg.jpg",
          address: "23 Kent Terrace, Mount Victoria, Wellington 6011",
          lat:"-41.2952101",
          lng:"174.7836867",
          phone: "0064272492589",
          description: "Real, delicious, plant-based Mexican food. Food for life: plant-based tacos, salads and soups.La Boca Loca’s clean-eating, veggie-loving little sister. Mexican the way your mama’s mama’s mama made it. No nasties, no short-cuts and no compromise on flavour.",
          is_meat: false,
          is_vegan: true,
          is_breakfast: true,
          is_dinner: true,
          is_dinein: true,
          is_takeaway: true
        }

      ]);
    });
};
